.compile: &compile
  configure_script: meson -Db_lundef=false build
  compile_script: ninja -C build

.test: &test
  test_script: ninja -C build test

.pipeline: &pipeline
  info_script: |
    meson --version
    ninja --version
  <<: *compile
  <<: *test

.python_env: &python_env
  python_env_setup_script: |
    python3 -m pip install --break-system-packages cram==0.7

FreeBSD_task:
  freebsd_instance:
    image_family: freebsd-14-2
  setup_script: |-
    pkg install -y gettext-tools pkgconf cmake meson git libffi libgit2 nanomsg
    python3 -m ensurepip
  <<: *python_env
  <<: *pipeline

Windows (mingw-gcc)_task:
  windows_container:
    image: cirrusci/windowsservercore:cmake
    os_version: 2019
  env:
    PATH: C:\\Python;C:\\Python\\Scripts;C:\\ProgramData\\chocolatey\\lib\\ninja\\tools;%PATH%
  setup_script: |-
    choco install -y --no-progress python313 --params "/InstallDir:C:\Python"
    choco install -y --no-progress ninja cmake
    pip install meson cram==0.7
    git config --global core.autocrlf false
    patch --forward --directory="C:\\Python\\Lib\\site-packages\\cram" < ci/cram-fix-winenv.patch
    patch --forward --directory="C:\\Python\\Lib\\site-packages\\cram" < ci/cram-ignore-cr.patch
  <<: *compile
  test_script: meson devenv -C build ninja test
