.compile: &compile
  configure_script: meson -Db_lundef=false build
  compile_script: ninja -C build

.test: &test
  test_script: ninja -C build test

.pipeline: &pipeline
  info_script: |
    meson --version
    ninja --version
  <<: *compile
  <<: *test

.python_env: &python_env
  python_env_setup_script: |
    python3 -m pip install --break-system-packages cram==0.7

FreeBSD_task:
  freebsd_instance:
    image_family: freebsd-14-2
  setup_script: |-
    pkg install -y gettext-tools pkgconf cmake meson git libffi libgit2 nanomsg
    python3 -m ensurepip
  <<: *python_env
  <<: *pipeline
