/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0 */

#include "criterion.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(criterion_protocol_birth, criterion_protocol_birth, AUTO)


PB_BIND(criterion_protocol_phase, criterion_protocol_phase, AUTO)


PB_BIND(criterion_protocol_death, criterion_protocol_death, AUTO)


PB_BIND(criterion_protocol_statistic, criterion_protocol_statistic, AUTO)


PB_BIND(criterion_protocol_param_entry, criterion_protocol_param_entry, AUTO)


PB_BIND(criterion_protocol_param_list, criterion_protocol_param_list, AUTO)


PB_BIND(criterion_protocol_result, criterion_protocol_result, AUTO)


PB_BIND(criterion_protocol_assert, criterion_protocol_assert, AUTO)


PB_BIND(criterion_protocol_log, criterion_protocol_log, AUTO)


PB_BIND(criterion_protocol_ack, criterion_protocol_ack, AUTO)


PB_BIND(criterion_protocol_submessage, criterion_protocol_submessage, AUTO)


PB_BIND(criterion_protocol_msg, criterion_protocol_msg, AUTO)







