name: Binaries

on:
  workflow_call:
    inputs:
      tarball-artifact:
        required: false
        type: string
      binaries-artifact:
        required: false
        type: string
      version:
        required: false
        type: string
  workflow_dispatch:

jobs:
  binaries:
    name: "Binaries"
    runs-on: ubuntu-latest
    # glibc v2.28 builder
    container: almalinux:8

    env:
      version: ${{ inputs.version || 'test' }}

    steps:
      - name: Install build dependencies
        run: |
          dnf install --assumeyes epel-release
          dnf install --assumeyes python3-pip cmake pkgconf gcc gcc-c++ git
          python3 -m pip install meson ninja

      - name: Download source tarball
        if: ${{ inputs.tarball-artifact }}
        uses: actions/download-artifact@v5
        with:
          name: ${{ inputs.tarball-artifact }}

      - name: Extract source tarball
        if: ${{ inputs.tarball-artifact }}
        run: |
          tar -xf "criterion-${version}.tar.xz" && rm "criterion-${version}.tar.xz"

      - name: Checkout Criterion
        if: ${{ !inputs.tarball-artifact }}
        uses: actions/checkout@v5

      - name: Build Criterion
        run: |
          srcdir="."

          if [ -n "${{ inputs.tarball-artifact }}" ]; then
            srcdir="criterion-${version}"
          fi

          meson setup -Dc_std=gnu11 --prefix /usr/local --libdir lib --buildtype plain --wrap-mode=forcefallback \
            build $src_dir
          meson compile -C build
          meson install -C build --skip-subprojects --destdir "$(realpath .)/binaries/criterion-${version}"

      - name: Create binary tarball
        run: |
          tar --create --xz --file "binaries/criterion-${version}-linux-x86_64.tar.xz" \
            --exclude='*.a' --transform="s,^\.,criterion-${version}," \
            -C "binaries/criterion-${version}/usr/local" .

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.binaries-artifact || 'binaries' }}
          path: binaries/criterion-*.tar.xz
          if-no-files-found: error
